# Generated by Django 3.1.3 on 2020-12-14 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classify',
            name='label',
        ),
    ]
